package client;

import java.io.*;
import java.net.*;

public class FileTransfer {

    /**
     * Uploads a file to the server using a raw binary HTTP POST request.
     * Runs in a background thread to prevent GUI freezing.
     * @return the unique file ID generated by the server.
     */
    public static String uploadFile(String serverIp, int port, File file) throws IOException {
        String urlString = "http://" + serverIp + ":" + port + "/upload?name=" + URLEncoder.encode(file.getName(), "UTF-8");
        URL url = new URL(urlString);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("POST");
        conn.setDoOutput(true);
        conn.setRequestProperty("Content-Type", "application/octet-stream");
        conn.setRequestProperty("Content-Length", String.valueOf(file.length()));
        conn.setConnectTimeout(5000);
        conn.setReadTimeout(30000);

        try (FileInputStream fis = new FileInputStream(file);
             OutputStream os = conn.getOutputStream()) {
            
            byte[] buffer = new byte[8192];
            int bytesRead;
            while ((bytesRead = fis.read(buffer)) != -1) {
                os.write(buffer, 0, bytesRead);
            }
            os.flush();
        }

        int responseCode = conn.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_OK) {
            try (InputStream is = conn.getInputStream();
                 BufferedReader reader = new BufferedReader(new InputStreamReader(is, "UTF-8"))) {
                return reader.readLine(); // Server returns unique fileId
            }
        } else {
            throw new IOException("Server returned HTTP error code: " + responseCode);
        }
    }

    /**
     * Downloads a file from the server using HTTP GET and saves it locally.
     * Runs in a background thread to prevent GUI freezing.
     */
    public static void downloadFile(String serverIp, int port, String fileId, File destinationFile) throws IOException {
        String urlString = "http://" + serverIp + ":" + port + "/download?id=" + URLEncoder.encode(fileId, "UTF-8");
        URL url = new URL(urlString);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");
        conn.setConnectTimeout(5000);
        conn.setReadTimeout(30000);

        int responseCode = conn.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_OK) {
            try (InputStream is = conn.getInputStream();
                 FileOutputStream fos = new FileOutputStream(destinationFile)) {
                
                byte[] buffer = new byte[8192];
                int bytesRead;
                while ((bytesRead = is.read(buffer)) != -1) {
                    fos.write(buffer, 0, bytesRead);
                }
                fos.flush();
            }
        } else {
            throw new IOException("Server returned HTTP error code: " + responseCode);
        }
    }
}
